# Generated by Django 4.0.3 on 2022-04-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=50)),
                ('descricao', models.CharField(default=None, max_length=200)),
                ('fornecedor', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
